# Generated by Django 3.1.7 on 2021-05-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0005_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='work_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
